ALTER TABLE public.monthly_metrics
ADD COLUMN IF NOT EXISTS num_formulas_capsulas INT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS vendas_capsulas NUMERIC NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS custo_mp_emb_capsulas NUMERIC NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS num_formulas_dermato INT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS vendas_dermato NUMERIC NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS custo_mp_emb_dermato NUMERIC NOT NULL DEFAULT 0;
